wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 2000000
env_name:
  desc: null
  value: CustomHopper-source-v0
eval_env:
  desc: null
  value: CustomHopper-target-v0
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718815701
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.7.12
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
