wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.2
ent_coef:
  value: 0
gamma:
  value: 0.999
learning_rate:
  value: 0.01
n_epochs:
  value: 10
n_steps:
  value: 1024
vf_coef:
  value: 0.65
