wandb_version: 1

batch_size:
  value: 128
clip_range:
  value: 0.3
ent_coef:
  value: 0.1
gamma:
  value: 0.95
learning_rate:
  value: 0.001
n_epochs:
  value: 15
n_steps:
  value: 4096
vf_coef:
  value: 0.35
