wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.2
ent_coef:
  value: 0
gamma:
  value: 0.99
learning_rate:
  value: 0.001
n_epochs:
  value: 5
n_steps:
  value: 4096
vf_coef:
  value: 0.5
