wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0
gamma:
  value: 0.95
learning_rate:
  value: 0.0001
n_epochs:
  value: 10
n_steps:
  value: 1024
vf_coef:
  value: 0.65
