wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718214954
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.12
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 128
clip_range:
  desc: null
  value: 0.1
ent_coef:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.95
learning_rate:
  desc: null
  value: 0.001
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 1024
vf_coef:
  desc: null
  value: 0.35
