wandb_version: 1

batch_size:
  value: 64
clip_range:
  value: 0.1
ent_coef:
  value: 0.01
gamma:
  value: 0.999
learning_rate:
  value: 0.0003
n_epochs:
  value: 10
n_steps:
  value: 2048
vf_coef:
  value: 0.35
